# Configurazione Database PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/capstone
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configurazione JWT
jwt.secret=CiccioBelloHaLaBuaVuoleTe!1112023!
jwt.expiration=86400000

restaurant.cover-price=2.00

# Stampanti
printer.pizzeria.port=COM3
printer.pizzeria.name-hint=PRINTER_PIZZERIA
printer.cucina.name=PRINTER_CUCINA
printer.sala.name=PRINTER_SALA
printer.receipt.name=PRINTER_SALA

printer.pizzeria.max-retries=3
printer.pizzeria.retry-delay-ms=1500
printer.pizzeria.health-check-interval-ms=180000