# Configurazione Database PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/capstone
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configurazione JWT
jwt.secret=CiccioBelloHaLaBuaVuoleTe!1112023!
jwt.expiration=86400000

restaurant.cover-price=2.00